acccounts/urls.py
from django.conf.urls import url
from .import views

app_name='accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view , name="signup"),
    url(r'^login/$',views.login_view , name="login"),
    url(r'^logout/$',views.logout_view , name="logout"),
]

djangoexercise/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .import views as view
from .router import router
from rest_framework.authtoken import views
from contacts.forms import ContactForm,CreateContact
from leads.forms import LeadForm,CreateLead
from meetings.forms import MeetingForm,CreateMeeting

baseurl=r'^leads/'
urlpatterns = [
    path('admin/', admin.site.urls),
     url(r'^leads/',include('leads.urls')),
     url(baseurl,include('contacts.urls')),
      url(baseurl,include('meetings.urls')),
      url(r'^accounts/',include('acccounts.urls')),
      url(r'^$',view.home_page,name="home"),
      path('api/',include(router.urls)),
      path('api-token-auth/',views.obtain_auth_token,name='api-token-auth'),
      path('customers',view.CustomerWizard.as_view([CreateContact,CreateLead,CreateMeeting])),
      path('customers/all',view.CustomerWizard1.as_view(view.FORMS_REG))
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from django.conf.urls import url
from .import views


app_name='leads'
urlpatterns = [
    url(r'^$',views.lead_list,name="list"),
    url(r'^create/$',views.lead_create,name="create"),
    # url(r'^promote/<int:id>',views.lead_update,name="promote"),
    path('promote/<int:id>',views.lead_promote,name="promote"),
    path('<int:id>/detail',views.lead_detail,name="promote"),
    path('update/<int:id>',views.lead_update,name="update"),
    path('delete/<int:id>',views.lead_delete,name="delete"),
    path('api/leadlist',views.leadListview,name="apitest")
    # url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name="detail"),
    
]

templates/base_layout.html
{% load static %}
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link  rel="stylesheet" href="{%static 'styles.css'%}">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/leads">Home <span class="sr-only">(current)</span></a>
      </li>
      {%if user.is_authenticated%}
    {% else %}
    
    {%endif%}
    </ul>
     {%if user.is_authenticated%}
     <h5 style="margin-right:70px;">USER : <strong>{{user.username}}</strong></h5>
    <form class="form-inline my-2 my-lg-0" action="{% url 'accounts:logout'%}" method="POST">
    {% csrf_token %}
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Logout</button>
    </form>
    {%else%}
     <div class="lef-nav">
     <ul>
     <li>
    <a class="btn btn-outline-secondary" href="{%url 'accounts:login'%}">Login</a></li>
    <li class="signup-li">
    <a class="btn btn-outline-secondary" href="{%url 'accounts:signup'%}">SignUp</a>
    </li>
     </ul>
     </div>
    {%endif%}
  </div>
</nav>
<div class="wrapper">
    {% block content %}
    {% endblock  %}
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/customer_form.html
<html>
<head>
</head>
<body>
<h2>Please Fill The Form</h2>
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {{ form }}
    {% endfor %}
{% else %}
    {{ wizard.form }}
{% endif %}
</table>
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">first step</button>
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">prev step</button>
{% endif %}
<input type="submit" value="submit"/>
</form>
</body>
</html>

templates/done.html
<html>
<head>
</head>
<body>
   {% for form in form_data%}
   {{form}}
   {% endfor %}
</body>
</html>

templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
<div class="center-h1">
<H1>WELCOME TO MARKETING MASTER</h1>
</div>
</div>
{% endblock  %}

templates/reg_step1.html
<html>
<head>
</head>
<body>
<h2>Please Fill The Form of Contact</h2>
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post">{% csrf_token %}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {{ form }}
    {% endfor %}
{% else %}
    {{ wizard.form }}
{% endif %}
</table>
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">first step</button>
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">prev step</button>
{% endif %}
<input type="submit" value="submit"/>
</form>
</body>
</html>

templates/reg_step2.html
<html>
<head>
</head>
<body>
<h2>Please Fill The Form of Lead</h2>
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post">{% csrf_token %}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {{ form }}
    {% endfor %}
{% else %}
    {{ wizard.form }}
{% endif %}
</table>
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">first step</button>
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">prev step</button>
{% endif %}
<input type="submit" value="submit"/>
</form>
</body>
</html>

templates/reg_step3.html
<html>
<head>
</head>
<body>
<h2>Please Fill The Form of Meeting</h2>
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post">{% csrf_token %}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {{ form }}
    {% endfor %}
{% else %}
    {{ wizard.form }}
{% endif %}
</table>
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">first step</button>
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">prev step</button>
{% endif %}
<input type="submit" value="submit"/>
</form>
</body>
</html>